import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [ques, setQues] = useState("")
  const [color, setColor] = useState("hidden")
  const [color2, setColor2] = useState("hidden")
  const [difficulty, setDifficulty] = useState("")
  const [data, setData] = useState([])
  
  const startQuiz = async () =>{
    setColor('hidden')
    setColor2('block')
    if(difficulty != "" && ques != ""){
      const data =  await fetch(`https://opentdb.com/api.php?encode=base64&token=da8a4fe7f6d9296e5cbeec5c0e5216a6a5472248257161dc91c821cb53f05d1f&amount=${ques}&difficulty=${difficulty}`)
      const myData = await data.json()
      await setData(myData.results)
    }
    else if(ques != ""){
      const data = await fetch(`https://opentdb.com/api.php?encode=base64&token=da8a4fe7f6d9296e5cbeec5c0e5216a6a5472248257161dc91c821cb53f05d1f&amount=${ques}`)
      const myData = await data.json()
      await setData(myData.results)
    }
    else{
      alert("Please Enter No. Of Questions")
    }
  }
  return (
    <>
      <Head>
        <title>Quiz Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gradient-to-r from-violet-500 to-fuchsia-500 py-[20vh] w-screen min-h-screen flex flex-col justify-center items-center'>
        <div className="w-1/2 h-[60vh] bg-white rounded-xl p-5 mx-auto flex flex-col justify-between items-center">
          <h1 className='text-2xl text-center font-bold uppercase my-2 text-violet-500'>Welcome to the ultimate quiz game </h1>
          <div className="input flex flex-col w-[80%] my-2">
            <label>Enten The No. Of Questions You Want</label>
            <input type="number" value={ques} placeholder="Between 1 and 50" onChange={e => setQues(e.target.value)} className='w-full p-2 my-1 rounded-xl border-2 border-slate-900'/>
          </div>
          <div className="input flex flex-col w-[80%] my-2">
            <label>Choose Difficulty</label>
            <select className='w-full p-2 my-1 rounded-xl border-2 border-slate-900'>
              <option value="any" onClick={()=>setDifficulty("")}>Any</option>
              <option value="hard" onClick={()=>setDifficulty("hard")}> Hard</option>
              <option value="medium" onClick={()=>setDifficulty("medium")}> Medium</option>
              <option value="easy" onClick={()=>setDifficulty("easy")}> Easy</option>
            </select>
          </div>


          <button className="text-center text-white rounded-xl bg-gradient-to-r from-violet-500 to-fuchsia-500  font-bold p-4 px-8 mb-4" onClick={()=>startQuiz()}>
            Start Quiz
          </button>



        </div>
        <div className={`w-[80vw] p-5 bg-white rounded-xl my-20 mx-auto ${color2}`}>
          {data.map(
            (quiz)=>{
              console.log(quiz)
              return <>
              <div className="flex flex-col p-5 my-5">
              <h1 key={quiz.question} className="my-2">{atob(quiz.question)}</h1>
              <h2 className={`my-2 ${color}`}>Ans: {atob(quiz.correct_answer)}</h2>
              
              </div>
              </>
            }
          )}
          <button className="text-center text-white rounded-xl bg-gradient-to-r from-violet-500 to-fuchsia-500  font-bold p-5 px-20 mb-4 fixed right-10 bottom-10 border-8 border-slate-800" onClick={()=>setColor("block")}>
            Show Answers
          </button>
          </div>
      </main>
    </>
  )
}
